version: '3.8'
services:
  crear-base:
    image: hub.siu.edu.ar:5005/siu/expedientes/docs-api:1.3.1
    env_file: 
      - ../docs.env
    secrets:
      - docs_db_pass
      - docs_api_pass
    entrypoint: # --db-initialize --create-db también crea la db
      - /entrypoint.sh
      - --reconfigure
      - --db-initialize
    networks:
      red-siu:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none

secrets:
  docs_db_pass:
    external: true
  docs_api_pass:
    external: true
    
networks:
  red-siu:
    external: true
