version: '3.8'
services:
  idm:
    image: hub.siu.edu.ar:5005/siu/expedientes/arai-usuarios/idm:v3.0.11
    env_file: 
      - ../usuarios.env
    secrets:
      - usuarios_db_pass
      - usuarios_ldap_admin_pass
      - usuarios_pass_salt
      - usuarios_idp_simplesaml_admin
    volumes:
      - ./files:/tmp/config_exportada
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    entrypoint: bash
    command:
      - -c
      - | 
        source /entrypoint.sh --export-secrets
        sed -i 's/\[arai_usuarios\]/\[arai_usuarios\]\nusar_perfiles_propios="1"/g' /usr/local/app/idm/instalacion/i__produccion/instancia.ini
        idm/bin/instalador instalacion:exportar -d /tmp/config_exportada --no-interaction --no-progress
    networks:
      red-siu:

secrets:
  usuarios_db_pass:
    external: true
  usuarios_ldap_admin_pass:
    external: true
  usuarios_pass_salt:
    external: true
  usuarios_idp_simplesaml_admin:
    external: true

networks:
  red-siu:
    external: true
